/**
 * Drizzle schema mirror of drizzle/0000_initial.sql.
 * Kept hand-curated (not autogenerated) so the file-of-record stays SQL.
 */
import {
  pgTable, serial, text, integer, boolean, timestamp, real, jsonb,
} from "drizzle-orm/pg-core";

export const projects = pgTable("projects", {
  id: serial("id").primaryKey(),
  slug: text("slug").notNull(),
  name: text("name").notNull(),
  domain: text("domain").notNull(),
  description: text("description"),

  primaryLocale: text("primary_locale").notNull(),
  timezone: text("timezone").notNull(),

  brandName: text("brand_name").notNull(),
  brandSuffix: text("brand_suffix").notNull(),
  brandColor: text("brand_color").notNull(),
  brandColorHover: text("brand_color_hover"),
  logoUrl: text("logo_url"),
  faviconUrl: text("favicon_url"),

  autoPublish: boolean("auto_publish").notNull().default(true),
  articleMinSources: integer("article_min_sources").notNull().default(2),
  maxNewsAgeHours: integer("max_news_age_hours").notNull().default(24),
  clusterInactivityHours: integer("cluster_inactivity_hours").notNull().default(24),

  ingestionCron: text("ingestion_cron").notNull(),
  generationCron: text("generation_cron").notNull(),

  // LLM provider config (v0.2). DB is the source of truth; .env's LLM_*
  // is only used as bootstrap for fresh installs / fallback.
  llmProvider: text("llm_provider").notNull().default("deepseek"),
  llmModel: text("llm_model").notNull().default("deepseek-chat"),
  llmApiKey: text("llm_api_key"),
  llmBaseUrl: text("llm_base_url"),

  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const users = pgTable("users", {
  id: serial("id").primaryKey(),
  projectId: integer("project_id").notNull(),
  username: text("username").notNull(),
  passwordHash: text("password_hash").notNull(),
  role: text("role").notNull().default("admin"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const sources = pgTable("sources", {
  id: serial("id").primaryKey(),
  projectId: integer("project_id").notNull(),
  name: text("name").notNull(),
  url: text("url").notNull(),
  type: text("type").notNull(),
  language: text("language").notNull(),
  tier: integer("tier").notNull(),
  isActive: boolean("is_active").notNull().default(true),
});

export const keywords = pgTable("keywords", {
  id: serial("id").primaryKey(),
  projectId: integer("project_id").notNull(),
  pattern: text("pattern").notNull(),
  isRegex: boolean("is_regex").notNull().default(false),
  category: text("category").notNull(),
  isActive: boolean("is_active").notNull().default(true),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const items = pgTable("items", {
  id: serial("id").primaryKey(),
  projectId: integer("project_id").notNull(),
  sourceId: integer("source_id").notNull(),
  title: text("title").notNull(),
  url: text("url").notNull(),
  summary: text("summary"),
  imageUrl: text("image_url"),
  language: text("language"),
  publishedAt: timestamp("published_at", { withTimezone: true }).notNull(),
  clusterId: integer("cluster_id"),
  skippedAt: timestamp("skipped_at", { withTimezone: true }),
});

export const clusters = pgTable("clusters", {
  id: serial("id").primaryKey(),
  projectId: integer("project_id").notNull(),
  headline: text("headline").notNull(),
  description: text("description"),
  sourceCount: integer("source_count").notNull().default(0),
  score: real("score").notNull().default(0),
  previousScore: real("previous_score"),
  isActive: boolean("is_active").notNull().default(true),
  lastSourceAddedAt: timestamp("last_source_added_at", { withTimezone: true }).notNull().defaultNow(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const articles = pgTable("articles", {
  id: serial("id").primaryKey(),
  projectId: integer("project_id").notNull(),
  clusterId: integer("cluster_id"),
  slug: text("slug").notNull(),
  title: text("title").notNull(),
  excerpt: text("excerpt"),
  contentHtml: text("content_html").notNull(),
  contentMarkdown: text("content_markdown"),
  imageUrl: text("image_url"),
  language: text("language").notNull(),
  status: text("status").notNull().default("published"),
  viewsCount: integer("views_count").notNull().default(0),
  isManual: boolean("is_manual").notNull().default(false),
  publishedAt: timestamp("published_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const staticPages = pgTable("static_pages", {
  id: serial("id").primaryKey(),
  projectId: integer("project_id").notNull(),
  slug: text("slug").notNull(),
  title: text("title").notNull(),
  contentMarkdown: text("content_markdown").notNull(),
  contentHtml: text("content_html").notNull(),
  isPublished: boolean("is_published").notNull().default(false),
  footerPosition: integer("footer_position"),
  locale: text("locale").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const botRuns = pgTable("bot_runs", {
  id: serial("id").primaryKey(),
  projectId: integer("project_id").notNull(),
  type: text("type").notNull(),
  startedAt: timestamp("started_at", { withTimezone: true }).notNull(),
  finishedAt: timestamp("finished_at", { withTimezone: true }),
  itemsAdded: integer("items_added"),
  clustersUpdated: integer("clusters_updated"),
  articlesCreated: integer("articles_created"),
  errors: jsonb("errors"),
  status: text("status").notNull(),
});

export type Project = typeof projects.$inferSelect;
export type Cluster = typeof clusters.$inferSelect;
export type Article = typeof articles.$inferSelect;
export type StaticPage = typeof staticPages.$inferSelect;
export type User = typeof users.$inferSelect;
export type Source = typeof sources.$inferSelect;
export type Keyword = typeof keywords.$inferSelect;
