#!/usr/bin/env bash
# Newsroom main installer. Orchestrates prerequisites → wizard → secrets →
# build → migrations → seed → start → TLS wait → summary.
#
# Invoked from /install.sh in repo root (which clones the repo if needed
# and re-execs this script).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# shellcheck source=lib/colors.sh
source "$SCRIPT_DIR/lib/colors.sh"
# shellcheck source=lib/prompts.sh
source "$SCRIPT_DIR/lib/prompts.sh"
# shellcheck source=lib/validators.sh
source "$SCRIPT_DIR/lib/validators.sh"
# shellcheck source=prerequisites.sh
source "$SCRIPT_DIR/prerequisites.sh"
# shellcheck source=wizard.sh
source "$SCRIPT_DIR/wizard.sh"

ANSWERS_FILE=${ANSWERS_FILE:-/tmp/newsroom-wizard.env}
SKIP_WIZARD=0
DOCKER_INSTALL=1

usage() {
    cat <<'EOF'
Newsroom installer.

Usage:
  install.sh                  Run interactive wizard, full install
  install.sh --resume         Skip wizard, reuse saved answers (after a prior failure)
  install.sh --skip-docker    Assume Docker is already installed
  install.sh --help           Show this message
EOF
}

while (( $# > 0 )); do
    case "$1" in
        --resume) SKIP_WIZARD=1 ;;
        --skip-docker) DOCKER_INSTALL=0 ;;
        --help|-h) usage; exit 0 ;;
        *) log_error "Unknown arg: $1"; usage; exit 1 ;;
    esac
    shift
done
export DOCKER_INSTALL

step_prerequisites() {
    run_prerequisites
}

step_wizard() {
    if (( SKIP_WIZARD )) && [[ -f "$ANSWERS_FILE" ]]; then
        log_info "Resuming with saved answers from $ANSWERS_FILE"
    else
        run_wizard
    fi
    # shellcheck source=/dev/null
    source "$ANSWERS_FILE"
}

step_write_env() {
    log_step "Generating secrets + writing .env"
    cd "$REPO_DIR"
    local pg_pw nx_secret site_address site_url db_url
    pg_pw=$(openssl rand -hex 32)
    nx_secret=$(openssl rand -base64 32 | tr -d '\n=')
    if [[ "$WIZ_DOMAIN" == "localhost" ]]; then
        site_address=":80"
        site_url="http://localhost"
    else
        site_address="$WIZ_DOMAIN"
        site_url="https://$WIZ_DOMAIN"
    fi
    db_url="postgresql://newsroom:${pg_pw}@postgres:5432/newsroom"
    umask 077
    cat > "$REPO_DIR/.env" <<EOF
# Generated by Newsroom installer on $(date -Iseconds)
SITE_ADDRESS=$site_address
SITE_URL=$site_url
POSTGRES_DB=newsroom
POSTGRES_USER=newsroom
POSTGRES_PASSWORD=$pg_pw
DATABASE_URL=$db_url
NEXTAUTH_SECRET=$nx_secret
PROJECT_SLUG=newsroom
PROJECT_DEFAULT_LOCALE=$WIZ_LOCALE
# LLM provider — wizard collected these. DB is the authoritative source
# (admin /admin/settings updates it). These env vars are bootstrap-only;
# the bot reads from the projects row on every run.
LLM_PROVIDER=${WIZ_LLM_PROVIDER:-deepseek}
LLM_MODEL=${WIZ_LLM_MODEL:-deepseek-chat}
LLM_API_KEY=${WIZ_LLM_API_KEY:-}
LLM_BASE_URL=${WIZ_LLM_BASE_URL:-}
NODE_ENV=production
TZ=$WIZ_TIMEZONE
EOF
    chmod 600 "$REPO_DIR/.env"
    log_ok ".env written (mode 0600). Secrets stay on this server only."
}

step_build() {
    log_step "Building Docker images (~5 min)"
    cd "$REPO_DIR"
    docker compose build
    log_ok "Images built"
}

step_start_postgres() {
    log_step "Starting Postgres (initial schema auto-applies)"
    cd "$REPO_DIR"
    docker compose up -d postgres
    local i=0
    while (( i < 30 )); do
        if docker compose exec -T postgres pg_isready -U newsroom -d newsroom >/dev/null 2>&1; then
            log_ok "Postgres healthy, schema applied"
            return 0
        fi
        sleep 2
        ((i++))
    done
    log_error "Postgres did not become healthy in 60 s. Last logs:"
    docker compose logs postgres | tail -30
    exit 1
}

step_seed() {
    log_step "Seeding project + admin + sources + keywords (preset: $WIZ_PRESET)"
    cd "$REPO_DIR"
    docker compose --profile manual run --rm \
        -v "$REPO_DIR/installer/presets:/presets:ro" \
        -e ADMIN_PASSWORD="$WIZ_ADMIN_PASSWORD" \
        bot python seed.py \
            --preset-file="/presets/${WIZ_PRESET}.yaml" \
            --slug=newsroom \
            --name="$WIZ_SITE_NAME" \
            --domain="$WIZ_DOMAIN" \
            --description="$WIZ_SITE_DESC" \
            --locale="$WIZ_LOCALE" \
            --timezone="$WIZ_TIMEZONE" \
            --brand-name="$WIZ_SITE_NAME" \
            --brand-suffix="$WIZ_BRAND_SUFFIX" \
            --brand-color="$WIZ_BRAND_COLOR" \
            --llm-provider="$WIZ_LLM_PROVIDER" \
            --llm-model="$WIZ_LLM_MODEL" \
            --llm-api-key="$WIZ_LLM_API_KEY" \
            --llm-base-url="$WIZ_LLM_BASE_URL"
    log_ok "Seed complete"
}

step_start_all() {
    log_step "Starting app + Caddy + bot-cron"
    cd "$REPO_DIR"
    docker compose up -d
    log_ok "All services up"
}

step_wait_tls() {
    if [[ "$WIZ_DOMAIN" == "localhost" ]]; then
        log_info "Skipping TLS wait (localhost)"
        return 0
    fi
    log_step "Waiting for Let's Encrypt certificate (~1-2 min)"
    local i=0
    while (( i < 60 )); do
        if curl -fsSL --max-time 3 "https://$WIZ_DOMAIN" -o /dev/null 2>/dev/null; then
            log_ok "TLS issued — https://$WIZ_DOMAIN responds"
            return 0
        fi
        sleep 5
        ((i++))
    done
    log_warn "TLS not ready after 5 min. Check 'docker compose logs caddy' — usually DNS / port 80 reachability."
}

step_summary() {
    log_step "Installation complete"
    local url
    if [[ "$WIZ_DOMAIN" == "localhost" ]]; then
        url="http://localhost"
    else
        url="https://$WIZ_DOMAIN"
    fi
    cat <<EOF

  ${GREEN}✓ Newsroom is live.${NC}

  Site:   $url
  Admin:  $url/admin   (login: admin, password: the one you set)

  Useful commands:
    cd $REPO_DIR
    docker compose ps               # service status
    docker compose logs -f          # follow logs
    ./upgrade.sh                    # pull latest + apply migrations (M6)
    ./scripts/reset-admin-password.sh   # if you forget the admin password

  Secrets live in $REPO_DIR/.env (mode 0600). Back it up before any disaster.

EOF
}

main() {
    step_prerequisites
    step_wizard
    step_write_env
    step_build
    step_start_postgres
    step_seed
    step_start_all
    step_wait_tls
    step_summary
}

main "$@"
